import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import { Sidebar } from '@/components/sidebar';
import { Topbar } from '@/components/top-bar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'VZ E-commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + ` grid min-h-screen w-full lg:grid-cols-[280px_1fr]`
        }
      >
        <Sidebar />
        <div className="flex flex-col">
          <Topbar />
          <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
